#### 捕获错误

render 阶段的核心代码如下：
发生错误会被捕获并交由 handleError 处理：

```js
do {
  try {
    // 对于并发更新则是workInLoopConcurrent
    workLoopSync();
    break;
  } catch (thrownValue) {
    handleError(root, thrownValue);
  }
} while (true);
```

commit 阶段包含很多工作，比如：

- 执行三个子阶段的 commitXXXEffectOnFiber
- 执行 componentDidMount/Update
- 绑定/解绑 ref
- 执行 useEffect/useLayoutEffect callback 与 destroy

这些工作会以如下形式执行，发生的错误会被捕获并交由 captureCommitPhaseError 处理：

```js
try {
  // ...
} catch (error) {
  captureCommitPhaseError(fiber, fiber.return, error);
}
```

#### 4.2.2 构造 callback

不管是 handleError 还是 capturePhaseError, 都会从“发生错误的 fiberNode 的父 fiberNode”开始，逐层向上遍历，寻找最近的 Error Boundaries。一旦找到，就会换行 createClassErrorUpdate 方法，构造如下两个 callback:

- 用于“执行 Error Boundaries API”的 callback
- 用于“抛出 React 提示信息”的 callback

```js
function createClassErrorUpdate(/* 省略参数 */) {
  // 为了增加代码的可读性，逻辑有删减
  if (typeof getDerivedStateFromError === "function") {
    // 用于执行getDerivedStateFromError的callback
    update.payload = () => {
      return getDerivedStateFromError(error);
    };

    // 用于抛出React提示信息的callback
    update.callback = () => {
      logCapturedError(fiber, errorInfo);
    };
  }

  if (inst !== null && typeof inst.componentDidCatch === "function") {
    // 用于执行componentDidCatch的callback
    update.callback = function callback() {
      this.componentDidCatch(error);
    };
  }

  return update;
}
```

如果没有找到 Error Boundaries, 则继续向上遍历直到 HostRootFiber,并执行 createRootErrorUpdate 方法构造 callback, 在 callback 内跑出“未捕获的错误”及“React 的提示信息”。

```js
function createRootErrorUpdate(/* 省略参数 */) {
  // ...
  // 用于抛出“未捕获的错误”及“React的提示信息”的callback
  update.callback = () => {
    onUncaughtError(error);
    logCapturedError(fiber, errorInfo);
  };

  return update;
}
```

#### 4.2.3 执行 callback

构造好的 callback 将在什么时候执行？React 中有两个”执行用户自定义 callback“的 API：

- 对于 ClassComponent, this.setState(newState, callback)中的 newState 和 callback 参数都能传递”函数类型参数“作为 callback.

对于 Error Boundaries，类似于触发一次如下所示的更新，这也是 Error Boundaries 属于 ClassComponent 特性的原因：

```js
this.setState(
  () => {
    // 用于执行getDerivedStateFromError的callback
  },
  () => {
    // 用于执行componentDidCatch的callback
    // 以及用于抛出React提示信息的callback
  }
);
```

- 对于 HostRoot, 执行 ReactDOM.render(element, container, callback)时，第三个参数 callback 接收一个回调函数作为”commit 阶段完成后的回调函数“。

  对于不存在 Error Boundaries 情况下发生的流程内错误，类似于执行如下函数：

  ```js
  ReactDOM.render(element, container, () => {
    // 用于抛出“未捕获的错误”及“React的提示信息”的callback
  });
  ```

  这些 callback 会在适当的时机执行，完成”错误处理“逻辑。
